"""initial canonical schema

Revision ID: c244a4254cb9
Revises: 
Create Date: 2026-09-16 02:35:42.547673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import academic_edge_domain.time  # noqa: F401  (custom UtcDateTime type rendering)


# revision identifiers, used by Alembic.
revision: str = 'c244a4254cb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('opportunity_types', sa.JSON(), nullable=False),
    sa.Column('market_types', sa.JSON(), nullable=False),
    sa.Column('min_net_edge_bps', sa.Integer(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_quote_age_seconds', sa.Integer(), nullable=False),
    sa.Column('require_actionable', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WATCH', 'ACTIONABLE', name='alertseverity', native_enum=False, length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_alert_rule_name')
    )
    with op.batch_alter_table('alert_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rule_created_at'), ['created_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('INGEST_RUN', 'RESOLUTION_DECISION', 'ALERT_RAISED', 'ALERT_ACKNOWLEDGED', 'POLICY_CHANGE', 'POLICY_VIOLATION', 'LEDGER_ENTRY', 'MODEL_REGISTERED', 'MANUAL_IMPORT', name='auditaction', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.Enum('READER', 'ANALYST', 'ADMIN', name='role', native_enum=False, length=32), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_occurred', ['action', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_occurred', ['occurred_at'], unique=False)

    op.create_table('ingest_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_ingest_run_source_started', ['source_id', 'started_at'], unique=False)

    op.create_table('model_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('trained_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('train_window_start', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('train_window_end', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('calibration_window_start', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('calibration_window_end', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_version_created_at'), ['created_at'], unique=False)

    op.create_table('source_health_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('checked_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('parser_drift_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_health_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_health_snapshot_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_source_health_source_checked', ['source_id', 'checked_at'], unique=False)

    op.create_table('source_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('vendor_url', sa.String(length=256), nullable=True),
    sa.Column('docs_url', sa.String(length=256), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PUBLIC', 'PUBLIC_READ', 'MANUAL', 'PAID', 'SYNTHETIC', name='sourcetier', native_enum=False, length=32), nullable=False),
    sa.Column('license', sa.String(length=512), nullable=False),
    sa.Column('auth', sa.String(length=40), nullable=False),
    sa.Column('quota_notes', sa.String(length=512), nullable=True),
    sa.Column('automation_allowed', sa.Boolean(), nullable=False),
    sa.Column('automation_scope', sa.Enum('OFFICIAL_API_ONLY', 'DOCUMENTED_PUBLIC_READS', 'BULK_STATIC_DOWNLOAD', 'MANUAL_CSV_ONLY', 'LOCAL_FIXTURES', name='automationscope', native_enum=False, length=32), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('terms_reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('terms_reviewed_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('data_classes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=False),
    sa.Column('registry_version', sa.Integer(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_source_policy_id')
    )
    with op.batch_alter_table('source_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_policy_created_at'), ['created_at'], unique=False)

    op.create_table('sport',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Enum('FOOTBALL', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sport_created_at'), ['created_at'], unique=False)

    op.create_table('venue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key', name='uq_venue_canonical_key')
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_created_at'), ['created_at'], unique=False)

    op.create_table('competition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('provider_tags', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'canonical_key', name='uq_competition_identity')
    )
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_created_at'), ['created_at'], unique=False)

    op.create_table('participant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'canonical_key', name='uq_participant_identity')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_created_at'), ['created_at'], unique=False)

    op.create_table('raw_payload',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('fetched_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('provider_timestamp', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('redaction_notes', sa.String(length=256), nullable=True),
    sa.Column('ingest_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_fingerprint', name='uq_raw_payload_fingerprint')
    )
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payload_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_raw_payload_source_fetched', ['source_id', 'fetched_at'], unique=False)

    op.create_table('participant_alias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('alias_raw', sa.String(length=200), nullable=False),
    sa.Column('alias_normalized', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalized', 'source_id', name='uq_alias_source')
    )
    with op.batch_alter_table('participant_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_alias_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_participant_alias_lookup', ['alias_normalized'], unique=False)

    op.create_table('season',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'label', name='uq_season_label')
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_created_at'), ['created_at'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('home_participant_id', sa.Uuid(), nullable=False),
    sa.Column('away_participant_id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('start_time_utc', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('round_label', sa.String(length=64), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['home_participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_competition_start', ['competition_id', 'start_time_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_event_start_time', ['start_time_utc'], unique=False)

    op.create_table('feature_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('missing_features', sa.JSON(), nullable=False),
    sa.Column('is_point_in_time_safe', sa.Boolean(), nullable=False),
    sa.Column('computed_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'as_of', 'feature_set_version', name='uq_feature_point')
    )
    with op.batch_alter_table('feature_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_feature_event_asof', ['event_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_snapshot_created_at'), ['created_at'], unique=False)

    op.create_table('injury_availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('reported_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injury_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injury_availability_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_injury_event_reported', ['event_id', 'reported_at'], unique=False)

    op.create_table('lineup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('coach', sa.String(length=120), nullable=True),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', 'is_confirmed', name='uq_lineup_state')
    )
    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineup_created_at'), ['created_at'], unique=False)

    op.create_table('market',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('market_type', sa.Enum('FT_1X2', 'FT_TOTALS_2_5', 'FT_BTTS', name='markettype', native_enum=False, length=32), nullable=False),
    sa.Column('period', sa.Enum('FULL_TIME', 'FIRST_HALF', 'SECOND_HALF', name='marketperiod', native_enum=False, length=32), nullable=False),
    sa.Column('line_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('team_scope', sa.Enum('HOME', 'AWAY', 'NEUTRAL', name='teamscope', native_enum=False, length=32), nullable=False),
    sa.Column('overtime_included', sa.Boolean(), nullable=False),
    sa.Column('settlement_version', sa.String(length=24), nullable=False),
    sa.Column('identity_key', sa.String(length=200), nullable=False),
    sa.Column('settlement_rule', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('line_value >= 0', name='ck_market_line_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'identity_key', name='uq_market_identity')
    )
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_market_event_type', ['event_id', 'market_type'], unique=False)

    op.create_table('prediction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('market_type', sa.Enum('FT_1X2', 'FT_TOTALS_2_5', 'FT_BTTS', name='markettype', native_enum=False, length=32), nullable=False),
    sa.Column('outcome_kind', sa.Enum('HOME', 'DRAW', 'AWAY', 'OVER', 'UNDER', 'YES', 'NO', name='outcomekind', native_enum=False, length=32), nullable=False),
    sa.Column('probability', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('fair_odds', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reason', sa.String(length=256), nullable=True),
    sa.Column('market_free', sa.Boolean(), nullable=False),
    sa.Column('as_of', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_prediction_prob'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'model_version_id', 'market_type', 'outcome_kind', name='uq_prediction_target')
    )
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_prediction_event_created', ['event_id', 'created_at'], unique=False)

    op.create_table('provider_event_map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_event_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('provider_competition_id', sa.String(length=64), nullable=True),
    sa.Column('provider_home_id', sa.String(length=64), nullable=True),
    sa.Column('provider_away_id', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.Enum('AUTO_ACCEPTED', 'REVIEW_REQUIRED', 'MANUALLY_LINKED', 'REJECTED', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('hard_reject_reasons', sa.JSON(), nullable=False),
    sa.Column('decided_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_id', sa.Uuid(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'provider_event_id', name='uq_provider_event')
    )
    with op.batch_alter_table('provider_event_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_event_map_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_provider_event_map_review', ['review_status'], unique=False)

    op.create_table('opportunity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('ARBITRAGE', 'POSITIVE_EV', 'MODEL_DISAGREEMENT', name='opportunitytype', native_enum=False, length=32), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('gross_edge_bps', sa.Integer(), nullable=False),
    sa.Column('net_edge_bps', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('best_legs', sa.JSON(), nullable=False),
    sa.Column('friction', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('total_stake', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('detected_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'market_id', 'opportunity_type', 'detected_at', name='uq_opportunity_point')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_opportunity_detected', ['detected_at'], unique=False)
        batch_op.create_index('ix_opportunity_type_detected', ['opportunity_type', 'detected_at'], unique=False)

    op.create_table('outcome',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_kind', sa.Enum('HOME', 'DRAW', 'AWAY', 'OVER', 'UNDER', 'YES', 'NO', name='outcomekind', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("label <> ''", name='ck_outcome_label_present'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'outcome_kind', name='uq_outcome_kind')
    )
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcome_created_at'), ['created_at'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_rule_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'EXPIRED', 'SUPPRESSED', name='alertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WATCH', 'ACTIONABLE', name='alertseverity', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('raised_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rule.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_alert_dedupe')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_alert_status_raised', ['status', 'raised_at'], unique=False)

    op.create_table('paper_ledger_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('stake', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SETTLED', 'VOID', name='ledgerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('placed_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('settled_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('decimal_odds > 1.0', name='ck_paper_ledger_odds_above_one'),
    sa.CheckConstraint('stake > 0', name='ck_paper_ledger_stake_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_ledger_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_paper_ledger_status_placed', ['status', 'placed_at'], unique=False)

    op.create_table('quote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('venue_kind', sa.Enum('BOOKMAKER', 'EXCHANGE', 'PREDICTION_MARKET', 'SYNTHETIC_FIXTURE', name='venuekind', native_enum=False, length=32), nullable=False),
    sa.Column('venue_name', sa.String(length=80), nullable=False),
    sa.Column('provider_market_id', sa.String(length=160), nullable=True),
    sa.Column('provider_outcome_id', sa.String(length=160), nullable=True),
    sa.Column('decimal_odds', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('available_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('observed_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('provider_timestamp', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('received_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('freshness', sa.Enum('FRESH', 'AGING', 'STALE', name='freshnesslabel', native_enum=False, length=32), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('raw_payload_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_size >= 0', name='ck_quote_size_non_negative'),
    sa.CheckConstraint('decimal_odds > 1.0', name='ck_quote_odds_above_one'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_quote_market_observed', ['market_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_quote_outcome_observed', ['outcome_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_quote_source_observed', ['source_id', 'observed_at'], unique=False)

    op.create_table('quote_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('best_decimal_odds', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('best_source_id', sa.String(length=64), nullable=False),
    sa.Column('implied_probability', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('fair_probability', sa.Numeric(precision=12, scale=9), nullable=True),
    sa.Column('de_vig_method', sa.Enum('MULTIPLICATIVE', 'POWER', name='devigmethod', native_enum=False, length=32), nullable=True),
    sa.Column('overround', sa.Numeric(precision=12, scale=9), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('freshest_observed_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outcome_id', 'as_of', name='uq_quote_snapshot_point')
    )
    with op.batch_alter_table('quote_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_snapshot_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_quote_snapshot_market_asof', ['market_id', 'as_of'], unique=False)

    op.create_table('settlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GRADED', 'VOID', 'ABANDONED', name='settlementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=24), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('settled_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', academic_edge_domain.time.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'rule_version', name='uq_settlement_market_rule')
    )
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_created_at'))

    op.drop_table('settlement')
    with op.batch_alter_table('quote_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_quote_snapshot_market_asof')
        batch_op.drop_index(batch_op.f('ix_quote_snapshot_created_at'))

    op.drop_table('quote_snapshot')
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_index('ix_quote_source_observed')
        batch_op.drop_index('ix_quote_outcome_observed')
        batch_op.drop_index('ix_quote_market_observed')
        batch_op.drop_index(batch_op.f('ix_quote_created_at'))

    op.drop_table('quote')
    with op.batch_alter_table('paper_ledger_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_paper_ledger_status_placed')
        batch_op.drop_index(batch_op.f('ix_paper_ledger_entry_created_at'))

    op.drop_table('paper_ledger_entry')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_status_raised')
        batch_op.drop_index(batch_op.f('ix_alert_created_at'))

    op.drop_table('alert')
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcome_created_at'))

    op.drop_table('outcome')
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunity_type_detected')
        batch_op.drop_index('ix_opportunity_detected')
        batch_op.drop_index(batch_op.f('ix_opportunity_created_at'))

    op.drop_table('opportunity')
    with op.batch_alter_table('provider_event_map', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_event_map_review')
        batch_op.drop_index(batch_op.f('ix_provider_event_map_created_at'))

    op.drop_table('provider_event_map')
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_index('ix_prediction_event_created')
        batch_op.drop_index(batch_op.f('ix_prediction_created_at'))

    op.drop_table('prediction')
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_index('ix_market_event_type')
        batch_op.drop_index(batch_op.f('ix_market_created_at'))

    op.drop_table('market')
    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineup_created_at'))

    op.drop_table('lineup')
    with op.batch_alter_table('injury_availability', schema=None) as batch_op:
        batch_op.drop_index('ix_injury_event_reported')
        batch_op.drop_index(batch_op.f('ix_injury_availability_created_at'))

    op.drop_table('injury_availability')
    with op.batch_alter_table('feature_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_snapshot_created_at'))
        batch_op.drop_index('ix_feature_event_asof')

    op.drop_table('feature_snapshot')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_start_time')
        batch_op.drop_index(batch_op.f('ix_event_created_at'))
        batch_op.drop_index('ix_event_competition_start')

    op.drop_table('event')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_created_at'))

    op.drop_table('season')
    with op.batch_alter_table('participant_alias', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_alias_lookup')
        batch_op.drop_index(batch_op.f('ix_participant_alias_created_at'))

    op.drop_table('participant_alias')
    with op.batch_alter_table('raw_payload', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_payload_source_fetched')
        batch_op.drop_index(batch_op.f('ix_raw_payload_created_at'))

    op.drop_table('raw_payload')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_created_at'))

    op.drop_table('participant')
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_created_at'))

    op.drop_table('competition')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_created_at'))

    op.drop_table('venue')
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sport_created_at'))

    op.drop_table('sport')
    with op.batch_alter_table('source_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_policy_created_at'))

    op.drop_table('source_policy')
    with op.batch_alter_table('source_health_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_source_health_source_checked')
        batch_op.drop_index(batch_op.f('ix_source_health_snapshot_created_at'))

    op.drop_table('source_health_snapshot')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_version_created_at'))

    op.drop_table('model_version')
    with op.batch_alter_table('ingest_run', schema=None) as batch_op:
        batch_op.drop_index('ix_ingest_run_source_started')
        batch_op.drop_index(batch_op.f('ix_ingest_run_created_at'))

    op.drop_table('ingest_run')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index('ix_audit_action_occurred')

    op.drop_table('audit_log')
    with op.batch_alter_table('alert_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rule_created_at'))

    op.drop_table('alert_rule')
    # ### end Alembic commands ###
